### ISSUE TITLE
Not working on Windows or Linux

### ISSUE THREAD

**Issue by davidshen84** [MabezDev/m27q-kvm#3]
Hi,

My M27Q connects to my Windows system through DP and my Linux laptop through the USB-C.

When my m27q is connected to my Windows system, and I execute the command in an admin terminal, I get these messages.

```
Found device: Bus 001 Device 002: ID 048d:5702
Found device: Bus 001 Device 003: ID 8087:0029
Found device: Bus 003 Device 000: ID 10de:1ad8
Found device: Bus 001 Device 081: ID 2109:0817
Found device: Bus 001 Device 082: ID 046d:c52b
Found device: Bus 001 Device 080: ID 2109:2817
Found device: Bus 001 Device 084: ID 2109:8883
Failed to open device: Access
could not find m27q
```

If I execute the command on my Linux system, even with `sudo`, I get these messages.

```
Found device: Bus 002 Device 001: ID 1d6b:0003
Found device: Bus 001 Device 002: ID 0cf3:e300
Found device: Bus 001 Device 003: ID 0c45:6713
Found device: Bus 001 Device 001: ID 1d6b:0002
could not find m27q
```

The strange thing is when I switch the KVM to Linux, my peripherals do not work, but the monitor is working. Linux can detect the monitor and extend my desktop to the M27Q. My M27Q firmware version is *B21.0325.1*.

I wonder if I need to make some settings changes to my monitor to use this command.

**Comment by MabezDev** [comment]
My M27Q has a different PID to yours: https://github.com/MabezDev/m27q-kvm/blob/f900063fef3c29e29dc6f53912cc3b4b910cb376/src/main.rs#L16. Probably a different hardware revision, try forking and changing the PID and see if it works then. Hopefully the USB interface hasn't changed :pinched_fingers:.

**Comment by davidshen84** [comment]
Hi Scott,

I update my PID,
https://github.com/davidshen84/m27q-kvm/blob/master/src/main.rs#L16, but
when I tried to compile it, I got these errors on my Windows system.

```
error[E0599]: no method named `add_quit_item` found for mutable reference
`&mut tray_item::api::windows::TrayItemWindows` in the current scope
   --> src\main.rs:168:11
    |
168 |     inner.add_quit_item("Quit");
    |           ^^^^^^^^^^^^^ help: there is an associated function with a
similar name: `add_menu_item`

error[E0599]: no method named `display` found for mutable reference `&mut
tray_item::api::windows::TrayItemWindows` in the current scope
   --> src\main.rs:169:11
    |
169 |     inner.display();
    |           ^^^^^^^ method not found in `&mut
tray_item::api::windows::TrayItemWindows`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `m27q-kvm` due to 2 previous errors
```

**Comment by MabezDev** [comment]
Hi @davidshen84, I don't think I'll be able to look at this for a while. If you can spare the time, could you try and fix the dependency issues and PR them?

**Comment by davidshen84** [comment]
I don't think I will have time to work on this. But regarding my original issue. I realised it was caused by my Linux kernel configuration error. I think this issue is no longer relevant.
